version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/backend/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/backend/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "daily"
