version: "3.9"

services:
  db:
    image: postgres:16.0-alpine3.18
    container_name: render-db
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: "render"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "render-local"
