services:
  db:
    image: postgres:15.5-alpine3.18
    container_name: ktlog-db
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: "ktlog"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "ktlog"
