spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:15432}/${POSTGRES_DB:ktlog}
    username: ${POSTGRES_USER:ktlog}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    show-sql: true
    generate-ddl: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true

  cache:
    type: none

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: "${GITHUB_CLIENT_ID}"
            client-secret: "${GITHUB_CLIENT_SECRET}"
            authorization-grant-type: authorization_code
            scope:
              - user:email
              - read:user

  threads:
    virtual:
      enabled: true

server:
  port: 18080

logging:
  level:
    org:
      springframework:
        security: DEBUG
