spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:15432}/${POSTGRES_DB:ktlog}
    username: ${POSTGRES_USER:ktlog}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    show-sql: true
    generate-ddl: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true

  cache:
    type: caffeine
    cache-names: getArticles,getArticle
    caffeine:
      spec: expireAfterWrite=4h,maximumSize=100

server:
  port: 18080
