spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/render-local
    username: "render"
    password: "password"

  jpa:
    show-sql: true
    generate-ddl: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
