spring:
  cache:
    type: caffeine
    cache-names: getArticles,getArticle
    caffeine:
      spec: expireAfterWrite=1h,maximumSize=100

server:
  port: 5000

application:
  cookie:
    secure: true
