spring:
  datasource:
    url: jdbc:postgresql://${KTLOG_POSTGRES_HOST:localhost}:${KTLOG_POSTGRES_PORT:15432}/${KTLOG_POSTGRES_DB:ktlog}
    username: ${KTLOG_POSTGRES_USER:ktlog}
    password: ${KTLOG_POSTGRES_PASSWORD:password}

  jpa:
    show-sql: true
    generate-ddl: false
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true

  cache:
    type: none

  threads:
    virtual:
      enabled: true

server:
  port: 18080

jwt:
  key: 0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
  access-token-expiration: 3600000 # 1,000 hours
  refresh-token-expiration: 86400000 # 1,000 days

logging:
  level:
    org:
      springframework:
        security: DEBUG
