name: Unit Tests

on:
  push:
    branches-ignore:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Test Frontend with Vitest
        run: |
          cd frontend
          npm install
          npx vitest run

      - name: Build Frontend so that Backend can host it
        run: |
          cd frontend
          npx vite build --outDir ./dist

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.OS }}-gradle-${{ hashFiles('backend/**.gradle*', 'backend/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.OS }}-gradle-

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Spring Boot tests
        run: cd backend && ./gradlew test
