name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - name: Test Frontend with Vitest
        run: |
          cd frontend
          npm install
          npx vitest run

      - name: Build Frontend so that Backend can host it
        run: |
          cd frontend
          npx vite build --outDir ./dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build-artifacts
          path: ./frontend/dist/

  backend:
    needs: frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.OS }}-gradle-${{ hashFiles('backend/**.gradle*', 'backend/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.OS }}-gradle-

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Spring Boot tests
        run: cd backend && ./gradlew test

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend-build-artifacts
          path: backend/src/main/resources/static/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: mahata
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Calculate Docker Image tag
        run: |
          DATE=$(date -u +'%Y-%m-%d')
          DOCKER_IMAGE_TAG="mahata/ktlog:${DATE}-${GITHUB_SHA}"
          echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: backend
          push: true
          tags: mahata/ktlog:latest,${{ env.DOCKER_IMAGE_TAG }}

      - name: Deploy to Render
        run: |
          curl ${{ secrets.RENDER_DEPLOY_HOOK_URL}}?key=${{ secrets.RENDER_DEPLOY_HOOK_KEY }}
