name: CI/CD

on: push

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: frontend/package-lock.json
          node-version: "20"
          cache: npm

      - name: Test Frontend with Vitest
        run: |
          npm --prefix ./frontend install
          make t_frontend

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Run Spring Boot tests
        run: make t_backend
